apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  labels:
    app: api-gateway
spec:
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 80   # Standard HTTP port for external access
      targetPort: 8000 # Port the API Gateway container is listening on
  type: LoadBalancer # Expose the service externally using a LoadBalancer
