apiVersion: v1
kind: Service
metadata:
  name: user-management-service
  labels:
    app: user-management
spec:
  selector:
    app: user-management
  type: 
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
---
